### ISSUE TITLE
So much flicking

### ISSUE THREAD

**Issue by ErAshu** [AmirShayegh/DatePicker#13]
Nice library. 
There should be one thing fix, on the very first time load of this library, the date is flicking so much.

I think this may becoz anywhere animation uses. 
Pls fix and also a black transparent view when present this.

**Comment by ronwood** [comment]
Perfect job and please fix the flicking

**Comment by ronwood** [comment]
How do I select the date when using the .displayPopOver?

**Comment by Datastore24Kirill** [comment]
fix the flicking

**Comment by AmirShayegh** [comment]
Fixed in 1.2.0
Sorry took me this long to get to it
